### ISSUE TITLE
Plotting with ST data (not visium)

### ISSUE THREAD

**Issue by ZheFrench** [lmweber/PrinciplesSTA#29]
Hi,
Recently, I have been through the book and some tools of the field.( Seurat, STutility , STexampleData, ggspavis)  

I was wondering if I miss the part where you explain how to plot with ST platform (the one from Stahl 2016).
It seems SpatialExperiment accept only Visium images to then overlap expression on the slide.

Is there a way to do that ? 
The easier/general method would be to plot a raster image without trying to have the slide in background  , no ?

Thanks.

**Comment by lmweber** [comment]
Apologies that we never replied to this issue. Closing the issue for now.
